---
apiVersion: v1
#kind: pod <- kind is case sensitive
kind: Pod
metadata:
    name: my-simple-todo-pod
    labels:
    app: simple-todo
    namespace: <YOUR NAMESPACE>
spec:
    containers:
    - name: test
#    image: sokubedoker/simple-todo:1.0 <- Typo !!!
    image: sokubedoker/simple-todo:1.0
    ports:
#    - containerPort: 80 <- In order to be visible in the landing zone (service) port is 8080
    - containerPort: 8080
    