---
apiVersion: v1
#kind: pod <- kind is case sensitive
kind: Pod
metadata:
  name: my-simple-todo-pod
  labels:
    app: simple-todo
spec:
  containers:
  - name: test
#    image: sokubedoker/simple-todo:1.0 <- Typo !!!
    image: sokubedocker/simple-todo:1.0
    imagePullPolicy: "Always"
    ports:
#      - containerPort: 80 <- In order to be visible in the landing zone (service) port is 8080
    - containerPort: 8080
    