---
apiVersion: v1
kind: Pod
metadata:
  name: my-simple-todo-pod
  labels:
    app: simple-todo
spec:
  containers:
  - name: test
    image: sokubedocker/simple-todo:1.0
    imagePullPolicy: "Always"
    ports:
    - containerPort: 8080
    env:
    - name: ORG
      value: <YOUR NAMESPACE>
    