---
apiVersion: v1
kind: pod
metadata:
  name: my-simple-todo-pod
  labels:
    app: simple-todo
spec:
  containers:
  - name: test
    image: sokubedoker/simple-todo:1.0
    imagePullPolicy: "Always"
    ports:
    - containerPort: 80
    