apiVersion: v1
kind: Service
metadata:
  name: my-app-example-2
  labels:
    app: my-app-example-2
spec:
  type: ClusterIP
  selector:
    app: my-app-example
  ports: 
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
