---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-deployment
  namespace: <YOUR NAMESPACE>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-todo
  template:
    metadata:
      labels:
        app: simple-todo
    spec:
      containers:
        - name: my-simple-todolist
          image: sokubedocker/simple-todo:2.0
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 1