---
apiVersion: v1
kind: Pod
metadata:
    name: my-simple-todo-pod
    labels:
    app: simple-todo
    namespace: <YOUR NAMESPACE>
spec:
    containers:
    - name: test
      image: sokubedocker/simple-todo:1.1
      ports:
      - containerPort: 8080
