---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-<YOURNAMESPACE>-pvc-with-sc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: jelastic-dynamic-volume
  resources:
    requests:
      storage: 10Mi
