---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-todo
  template:
    metadata:
      labels:
        app: simple-todo
    spec:
      containers:
        - name: my-simple-todolist
          image: sokubedocker/simple-todo:2.1
          env:
            - name: ORG
              value: <YOURNAMESPACE>
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: "/usr/src/app/static/css/css-additional"
              name: configmap-css-additional
      volumes:
        - configMap:
            name: configmap-css-additional
          name: configmap-css-additional
