---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-todo
  template:
    metadata:
      labels:
        app: simple-todo
    spec:
      containers:
        - name: my-simple-todolist
          image: mowhank/simple-todo-list:1.0.1
          ports:
          - containerPort: 8080
            livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: "/tmp"
              name: configmap-css-additional
      volumes:
        - configMap:
            name: configmap-css-additional
          name: configmap-css-additional
